### ISSUE TITLE
Breaks create-react-app's test script

### ISSUE THREAD

**Issue by pedro-mass** [prettier/prettier-eslint-cli#92] opened 2017-08-18 15:04 UTC
- `prettier-eslint-cli` version: 4.2.0
- `prettier` version: 1.5.3
- `eslint` version: 4.4.1
- `react-script` version: 1.0.11

Relevant code/config.

```javascript

```

What you did:

Just included `prettier-eslint-cli` in my `package.json` file.

What happened:

```
2017-08-18 10:56 node[9945] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-08-18 10:56 node[9945] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-08-18 10:56 node[9945] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1020:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
error Command failed with exit code 1.
```
Reproduction:

-- paste your link here --

Problem description:

Suggested solution:

**Comment by kentcdodds** [comment] 2017-08-18 15:30
Hi @pedro-mass,
I cannot reproduce this issue:

```
npx create-react-app my-app
cd my-app
yarn add --dev prettier-eslint-cli
yarn test
```

I tried it with `npm` as well. Everything worked without issue.

I'm going to go ahead and close this, but feel free to dig further and if you find that prettier-eslint-cli is a problem and have a suggested solution, feel free to comment and we can reopen the issue. Good luck!

**Closed by kentcdodds** 2017-08-18 15:30 UTC
