### ISSUE TITLE
I have problem about this package,

### ISSUE THREAD

**Issue by lockunlatui** [prettier/prettier-eslint-cli#392] opened 2021-05-08 11:58 UTC
- `prettier-eslint-cli` version:
- `prettier` version:
- `eslint` version:

Relevant code/config.

```javascript

```

What you did:

What happened:

Reproduction:

-- paste your link here --

Problem description:

Suggested solution:

**Comment by chrisbobbe** [comment] 2021-08-10 23:23
This issue is totally blank except for what looks like a new-issue template. Would you please close it or provide a detailed description of the problem (including, if you can, a minimal reproduction recipe for the bug, if it is a bug)? 🙂

**Closed** 2022-08-07 05:12 UTC
