### ISSUE TITLE
Pass in `fallbackPrettierOptions` instead of `prettierOptions`

### ISSUE THREAD

**Issue by ckknight** [prettier/prettier-eslint-cli#66] opened 2017-06-01 21:13 UTC
Given the availability of `fallbackPrettierOptions` with prettier-eslint v6, it seems wise to pass that in instead of `prettierOptions` as is done today.

The underlying issue is that I want the `comma-dangle` eslint option to dictate how files are prettified rather than specifying `--trailing-comma`.

**Comment by kentcdodds** [comment] 2017-06-01 21:17
Hmm... I'm pretty sure that you should only need to pass command line flags if you want to explicitly set an option. If you want `comma-dangle` to dictate how files are prettified, then just don't pass the flag and it will be inferred. If this isn't happening, please [reproduce the issue](https://github.com/kentcdodds/prettier-eslint-cli-repro) )

**Comment by kentcdodds** [comment] 2017-06-26 16:02
Closing due to inactivity

**Closed by kentcdodds** 2017-06-26 16:02 UTC
